name: Docker Image CI

on:
    release:
        types: [published]
    push:
        branches:
            - main
        tags:
            - "v*"
        paths:
            - "src/**"
            - "docker/*"
            - "!*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Get Docker tags
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: 1574242600/microsoft-rewards-script
                  tags: |
                      type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
                      type=pep440,pattern={{version}}
    
            - name: Build and push image
              id: build
              uses: docker/build-push-action@v6
              with:
                  file: ./docker/Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  platforms: linux/amd64,linux/arm64

            - name: Images digests
              run: echo ${{ steps.build.outputs.digest }}
